### ISSUE TITLE
Authenticating service account in Cloud Function

### ISSUE THREAD

**Issue by bhr** [googleapis/google-auth-library-nodejs#1069]
I've been trying to follow the code samples to get an access token from inside a cloud function for a service account. The goal is to pass that access token to another service which can then directly run functions through an ESP.

I've tried the following options without success:

### A
```
    const url = `https://cloud-run1234.a.run.app`;
    const auth = new GoogleAuth();
    const client = await auth.getIdTokenClient(url);
    const result = await client.request({url});
    console.log(result.data);
```

#### Error received in logs
`Error: [object Object] at Gaxios._request (/workspace/node_modules/gaxios/build/src/gaxios.js:89:23) at process._tickCallback (internal/process/next_tick.js:68:7)`

### B
```
    const url = `https://cloud-run1234.a.run.app`;
    const client = new Compute({
      serviceAccountEmail: '<service-account>@<project>.iam.gserviceaccount.com'
    });
    const clientToken = await client.fetchIdToken(url);
    console.log(clientToken);
```

#### Error received in logs
`Could not fetch ID token: Unsuccessful response status code. Request failed with status code 404 at Gaxios._request (/workspace/node_modules/gaxios/build/src/gaxios.js:89:23) at process._tickCallback (internal/process/next_tick.js:68:7)`

### More details

`https://cloud-run1234.a.run.app` is a cloud run instance to which the service account has permissions as Cloud Run Invoker and Cloud Functions Invoker.

I should also mention that I didn't set `GOOGLE_APPLICATION_CREDENTIALS`. If reading the docs correctly, then this should not be required when running inside a cloud function.

**Comment by bhr** [comment]
It seems I created the issue twice. Closing this one. See #1068
