### ISSUE TITLE
Getting metadata from plugin failed with error: request to https://www.googleapis.com/oauth2/v4/token failed, reason: connect ECONNREFUSED 142.250.74.202:443',

### ISSUE THREAD

**Issue by mohan570** [googleapis/google-auth-library-nodejs#1099]
Hi Team,

In recently last two months only we are getting below error while using detectTextIntent method( const responses = await sessionClient.detectIntent(request); ) in detect.js file( https://github.com/googleapis/nodejs-dialogflow/blob/master/samples/detect.js ).

The Error,

ERROR: Error: Getting metadata from plugin failed with error: request to https://www.googleapis.com/oauth2/v4/token failed, reason: connect ECONNREFUSED 142.250.74.202:443
at Http2CallStream. (API\node_modules\dialogflow\node_modules@grpc\grpc-js\build\src\client.js:102:45)
at Http2CallStream.emit (events.js:322:22)
at Http2CallStream.endCall (API\node_modules\dialogflow\node_modules@grpc\grpc-js\build\src\call-stream.js:74:18)
at API\node_modules\dialogflow\node_modules@grpc\grpc-js\build\src\call-stream.js:355:18
at runMicrotasks ()
at processTicksAndRejections (internal/process/task_queues.js:97:5) {
code: 'ECONNREFUSED',
details: 'Getting metadata from plugin failed with error: request to https://www.googleapis.com/oauth2/v4/token failed, reason: connect ECONNREFUSED 142.250.74.202:443',
metadata: Metadata { internalRepr: Map {} }

Regards,
Mohan A

**Comment by bcoe** [comment]
@mohan570 in what environment are you running your cloud function, and could you share a gist with as close to possible the code that you're running?

**Comment by mohan570** [comment]
**Server**
Server : windows 2008 r2
Node js : 12.16.2
Node js Diaglogflow Client (mulitple agent via .env variables)

Frontend - Angular

**Comment by bcoe** [comment]
@mohan570 how frequently are you seeing this error, the failure to connect to `142.250.74.202` suggests an intermittent connectivity issue to Google's servers:

* do you connect through a corporate proxy, and if so do you have the `http_proxy` variable set.
* how many agents are you running in parallel?

**Comment by mohan570** [comment]
-- do you connect through a corporate proxy, and if so do you have the http_proxy variable set. 
    - http_proxy and https_proxy are set via npm proxy config set

- how many agents are you running in parallel?
   - 5

**Comment by bcoe** [comment]
@mohan570 could you run your application explicitly with these proxy variables set, e.g.,

```
http_proxy=http://www.some-proxy https_proxy=http://some-proxy node my-agent.js
```

I'm not sure whether the `npm proxy config` applies to requests outside of the `npm install`?

**Comment by MobileApp631** [comment]
> @mohan570 could you run your application explicitly with these proxy variables set, e.g.,
> 
> ```
> http_proxy=http://www.some-proxy https_proxy=http://some-proxy node my-agent.js
> ```
> 
> I'm not sure whether the `npm proxy config` applies to requests outside of the `npm install`?

--- 
Hi Bcoe,

still its not working getting error, find below 

FetchError: request to https://www.googleapis.com/oauth2/v4/token failed, reason: connect ECONNREFUSED 142.250.74.202:443
2021-02-08 14:50 +01:00:     at ClientRequest.<anonymous> (\API\node_modules\node-fetch\lib\index.js:1444:11)
2021-02-08 14:50 +01:00:     at ClientRequest.emit (events.js:310:20)
2021-02-08 14:50 +01:00:     at TLSSocket.socketErrorListener (_http_client.js:426:9)
2021-02-08 14:50 +01:00:     at TLSSocket.emit (events.js:310:20)
2021-02-08 14:50 +01:00:     at emitErrorNT (internal/streams/destroy.js:92:8)
2021-02-08 14:50 +01:00:     at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
2021-02-08 14:50 +01:00:     at processTicksAndRejections (internal/process/task_queues.js:84:21) {
2021-02-08 14:50 +01:00:   message: 'request to https://www.googleapis.com/oauth2/v4/token failed, reason: connect ECONNREFUSED 142.250.74.202:443',
2021-02-08 14:50 +01:00:   type: 'system',
2021-02-08 14:50 +01:00:   errno: 'ECONNREFUSED',
2021-02-08 14:50 +01:00:   code: 'ECONNREFUSED',
2021-02-08 14:50 +01:00:   config: {
2021-02-08 14:50 +01:00:     method: 'POST',
2021-02-08 14:50 +01:00:     url: 'https://www.googleapis.com/oauth2/v4/token',
2021-02-08 14:50 +01:00:     data: {
2021-02-08 14:50 +01:00:       grant_type: 'urn:ietf:params:oauth:grant-type:jwt-bearer',
2021-02-08 14:50 +01:00:       assertion: 'encryptedkeyhash'
2021-02-08 14:50 +01:00:     },
2021-02-08 14:50 +01:00:     headers: { 'Content-Type': 'application/json', Accept: 'application/json' },
2021-02-08 14:50 +01:00:     responseType: 'json',
2021-02-08 14:50 +01:00:     params: [Object: null prototype] {},
2021-02-08 14:50 +01:00:     paramsSerializer: [Function: paramsSerializer],
2021-02-08 14:50 +01:00:     body: '{"grant_type":"urn:ietf:params:oauth:grant-type:jwt-bearer","assertion":"encryptedkeyhash"}',
2021-02-08 14:50 +01:00:     validateStatus: [Function: validateStatus]
2021-02-08 14:50 +01:00:   }
2021-02-08 14:50 +01:00: }

Thanks

**Comment by bcoe** [comment]
@MobileApp631 could you please provide a minimal example of the code that is not working for you?

Also, if possible, could you provide an example of the command you are using to start the application? how are the proxy variables being set?

**Comment by JustinBeckwith** [comment]
Closing due to inactivity
