### ISSUE TITLE
Error: Internal error encountered.

### ISSUE THREAD

**Issue by romarioj2h** [googleapis/google-auth-library-nodejs#1127]
#### Environment details

  - OS: Ubuntu 18.04 5.4.0-1037-oracle
  - Node.js version: v8.10.0
  - npm version: 3.5.2
  - `google-auth-library` version: 6.1.6

#### Steps to reproduce

  1. Trying to insert an item into a YouTube playlist
  2. Occurs sporadically

Additional details

```
UnhandledPromiseRejectionWarning: Error: Internal error encountered.
    at Gaxios._request (/home/ubuntu/top40ukgenerator/node_modules/google-auth-library/node_modules/gaxios/build/src/gaxios.js:113:23)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
(node:20389) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:20389) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

translatedResponse object:

```
{
  config: {
    url:
      "https://www.googleapis.com/youtube/v3/playlistItems?part=snippet&mine=true",
    method: "POST",
    userAgentDirectives: [[Object]],
    paramsSerializer: [Function],
    data: { snippet: [Object] },
    headers: {
      "x-goog-api-client": "gdcl/4.4.0 gl-node/8.10.0 auth/6.1.6",
      "Accept-Encoding": "gzip",
      "User-Agent": "google-api-nodejs-client/4.4.0 (gzip)",
      Authorization: "Bearer xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
      "Content-Type": "application/json",
      Accept: "application/json",
    },
    params: { part: "snippet", mine: true },
    validateStatus: [Function],
    retry: true,
    body:
      '{"snippet":{"playlistId":"PLfAwBbHA3N6fOINFmXT2264h51LfS_TlF","resourceId":{"kind":"youtube#video","videoId":"8TsWkuWWXgc"}}}',
    responseType: "json",
  },
  data: {
    error: {
      code: 500,
      message: "Internal error encountered.",
      errors: [
        {
          message: "Internal error encountered.",
          domain: "global",
          reason: "backendError",
        },
      ],
      status: "INTERNAL",
    },
  },
  headers: {
    "alt-svc":
      'h3-29=":443"; ma=2592000,h3-T051=":443"; ma=2592000,h3-Q050=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000,quic=":443"; ma=2592000; v="46,43"',
    "cache-control": "private",
    connection: "close",
    "content-encoding": "gzip",
    "content-type": "application/json; charset=UTF-8",
    date: "Tue, 02 Feb 2021 00:10:09 GMT",
    server: "scaffolding on HTTPServer2",
    "transfer-encoding": "chunked",
    vary: "Origin, X-Origin, Referer",
    "x-content-type-options": "nosniff",
    "x-frame-options": "SAMEORIGIN",
    "x-xss-protection": "0",
  },
  status: 500,
  statusText: "Internal Server Error",
  request: {
    responseURL:
      "https://www.googleapis.com/youtube/v3/playlistItems?part=snippet&mine=true",
  },
}
```

**Comment by sofisl** [comment]
Hi @romarioj2h, can you share your code snippet to reproduce? Thanks!

**Comment by romarioj2h** [comment]
Hi @sofisl, you can check the code at https://github.com/romarioj2h/top40ukgenerator/blob/master/youtube/playlistItems.js#L22

**Comment by JustinBeckwith** [comment]
Greetings @romarioj2h!  Sadly, this probably isn't something we can directly help with.  If the error is sporadic, and the result is a HTTP 500, it means there's something happening on the back end, independent of this library.  I'd suggest checking out the support channel for the YouTube API, where it looks like they direct folks through StackOverflow:
https://developers.google.com/youtube/v3/support
