### ISSUE TITLE
`fetchIdToken` fails with a 400 error when using the `Compute` client on GKE with Workload Identity

### ISSUE THREAD

**Issue by sjaq** [googleapis/google-auth-library-nodejs#1305]
#### Environment details
  - OS: Alpine Linux v3.11
  - Node.js version: v14.18.1
  - npm version: 6.14.15
  - `google-auth-library` version: 7.9.2

#### Steps to reproduce
  1. Run a container in GKE with Workload Identity configured
  2. Attempt to generate an ID token using the following code:

```js
const google = require('google-auth-library');
const client = await new google.GoogleAuth().getClient()
console.log(await client.fetchIdToken('IAP_CLIENT_ID'))

Uncaught:
GaxiosError: Could not fetch ID token: Unsuccessful response status code. Request failed with status code 400
    at Gaxios._request (/app/node_modules/gaxios/build/src/gaxios.js:129:23)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async metadataAccessor (/app/node_modules/gcp-metadata/build/src/index.js:68:21)
    at async Compute.fetchIdToken (/app/node_modules/google-auth-library/build/src/auth/computeclient.js:80:23)
    at async REPL4:1:36 {
  response: {
    config: {
      url: 'http://169.254.169.254/computeMetadata/v1/instance/service-accounts/default/identity?format=full&[SNIP].apps.googleusercontent.com',
      headers: [Object],
      retryConfig: [Object],
      responseType: 'text',
      timeout: 3000,
      paramsSerializer: [Function: paramsSerializer],
      validateStatus: [Function: validateStatus],
      method: 'GET'
    },
    data: 'non-empty audience parameter required\n',
    headers: {
      connection: 'close',
      'content-length': '38',
      'content-type': 'text/plain; charset=utf-8',
      date: 'Tue, 19 Oct 2021 10:50:12 GMT',
      'x-content-type-options': 'nosniff'
    },
    status: 400,
    statusText: 'Bad Request',
    request: {
      responseURL: 'http://169.254.169.254/computeMetadata/v1/instance/service-accounts/default/identity?format=full&audience=[SNIP].apps.googleusercontent.com'
    }
  },
  config: {
    url: 'http://169.254.169.254/computeMetadata/v1/instance/service-accounts/default/identity?format=full&audience=[SNIP].apps.googleusercontent.com',
    headers: { 'Metadata-Flavor': 'Google' },
    retryConfig: {
      noResponseRetries: 3,
      currentRetryAttempt: 0,
      retry: 3,
      httpMethodsToRetry: [Array],
      statusCodesToRetry: [Array]
    },
    responseType: 'text',
    timeout: 3000,
    paramsSerializer: [Function: paramsSerializer],
    validateStatus: [Function: validateStatus],
    method: 'GET'
  },
  code: '400'
}
```

#### Cause of issue
After some debugging what is going wrong it seems the Workload Identity Metadata server only accepts the `audience` query parameter if it is the first argument.

```sh
# Returns a valid token
$ wget -qO- --header="Metadata-Flavor: Google" http://169.254.169.254/computeMetadata/v1/instance/service-accounts/default/identity?audience=[snip].apps.googleusercontent.com&format=full
eyJhbGciOiJSUzI1NiIs[...snip...]

# Returns the same 400 error, note that only the order of the query params changed
$ wget -qO- --header="Metadata-Flavor: Google" http://169.254.169.254/computeMetadata/v1/instance/service-accounts/default/identity?format=full&audience=[snip].apps.googleusercontent.com
wget: server returned error: HTTP/1.1 400 Bad Request

**Comment by bcoe** [comment]
@sjaq thanks for digging into this, this is a somewhat fascinating bug.

@bojeil-google is this a known issue with the workload identify server, I'm wondering if we should open an internal bug.

**Comment by sjaq** [comment]
Thanks for looking into this!

Is this something that I need to work around in my implementation or something I can expect an update of the library for? Just want to prevent any unnecessary workaround in my codebase... Seems like an easy fix to reorder the query arguments in the library itself?

**Comment by bojeil-google** [comment]
Hey @sjaq, we will implement it the same way I am describing above (it is not a temporary fix or hack). So you can do it on your own if you can't wait. We want to eventually do it but we have to align across languages (we need to support in several languages and not just Node.js), so it may take time to get to it given the many projects in our pipeline at the moment.

**Comment by sjaq** [comment]
@bojeil-google I'm using workload identity as described [here](https://cloud.google.com/kubernetes-engine/docs/how-to/workload-identity) to run workloads that have a provided Google Service Account, when I use the nodejs client I'm provided with a `Compute` client as the default authorization client, not sure what I could do differently on my end?

**Comment by bcoe** [comment]
@sjaq I'm glad you've found a workaround that's doing the trick for you.

It seems like a nice feature would be if you could somehow upgrade a Compute client to a WorkLoadIdentityCompute client? Leaving this open as a feature request.
