### ISSUE TITLE
'Unknown error' trying to generate signed URL

### ISSUE THREAD

**Issue by igor47** [googleapis/google-auth-library-nodejs#1500]
I opened this as a bug in storage, here: https://github.com/googleapis/nodejs-storage/issues/2115

but this is probably an issue in this library? opening it in both places, since my current project has screeched to a halt over this issue :cry: 

Here's a script, which is almost exactly the example in google's documentation about how to generate signed URLs. It proces an error (i somehow got a deeper traceback on the other issue, but I can't figure out how to get that traceback now). using the same credential file with `gsutil` produces a working url, so it's not a permissions issue. this works:

```bash
$ gsutil signurl -d 15m -r asia-east-1 ./service-account.json  gs://mybucket/testfile
```

and this produces an `Unknown error`:

```node
import { Storage } from '@google-cloud/storage'
import { GoogleAuth } from 'google-auth-library'

// The ID of your GCS bucket
const bucketName = 'mybucket'

// The full path of your file inside the GCS bucket, e.g. 'yourFile.jpg' or 'folder1/folder2/yourFile.jpg'
const fileName = 'testfile'

// Creates a client
const storage = new Storage({
  authClient: new GoogleAuth({
    keyFile: '/home/igor47/service-account.json',
    scopes: 'https://www.googleapis.com/auth/cloud-platform',
  }),
})

async function generateV4ReadSignedUrl() {
  // These options will allow temporary read access to the file
  const options = {
    version: 'v4',
    action: 'read',
    expires: Date.now() + 15 * 60 * 1000, // 15 minutes
  } as const;

  // Get a v4 signed URL for reading the file
  const [url] = await storage
    .bucket(bucketName)
    .file(fileName)
    .getSignedUrl(options);

  console.log('Generated GET signed URL:');
  console.log(url);
  console.log('You can use this URL with any user agent, for example:');
  console.log(`curl '${url}'`);
}

generateV4ReadSignedUrl().catch(console.dir);
```

the best traceback i can get now is:
```
Error: Unknown error.
    at GoogleAuth.getCredentialsAsync (/home/igor47/repos/recoolit/node_modules/@google-cloud/storage/node_modules/google-auth-library/build/src/auth/googleauth.js:608:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async sign (/home/igor47/repos/recoolit/node_modules/@google-cloud/storage/build/src/signer.js:156:33)
```

**Comment by danielbankhead** [comment]
Duplicate: https://github.com/googleapis/nodejs-storage/issues/2115

Will follow-up with there.
