### ISSUE TITLE
Problem in CloudRun after upgrade to version 9.3.0

### ISSUE THREAD

**Issue by acarvalhotw** [googleapis/google-auth-library-nodejs#1705]
#### Environment details

  - GCP Cloud Run
  - nodejs version: 18.18.2-r0
  - `google-auth-library` version: 9.3.0

####
This problem happens when it tries to connect to a PubSub subscription
#### 
TypeError: gcpMetadata.universe is not a function
    at GoogleAuth._GoogleAuth_getUniverseFromMetadataServer (/app/node_modules/google-auth-library/build/src/auth/googleauth.js:777:44)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async GoogleAuth.getUniverseDomain (/app/node_modules/google-auth-library/build/src/auth/googleauth.js:186:168)
    at async GoogleAuth.getApplicationDefaultAsync (/app/node_modules/google-auth-library/build/src/auth/googleauth.js:252:42)
    at async GoogleAuth.getClient (/app/node_modules/google-auth-library/build/src/auth/googleauth.js:674:17)
    at async GrpcClient._getCredentials (/app/node_modules/google-gax/build/src/grpc.js:145:24)
    at async GrpcClient.createStub (/app/node_modules/google-gax/build/src/grpc.js:308:23)

Thanks!

**Comment by danielbankhead** [comment]
Fixed via:
- https://github.com/googleapis/google-auth-library-nodejs/pull/1704

I'm investigating what went wrong with our dependency update bot to prevent this issue in the future.
