### ISSUE TITLE
Unsuccessful response status code. Request failed with status code 404

### ISSUE THREAD

**Issue by matt-oakes** [googleapis/google-auth-library-nodejs#1706]
I am using the `google-auth-library` to run v2 Firebase task functions [as per the documentation](https://firebase.google.com/docs/functions/task-functions?gen=2nd#retrieve-and). After I deployed today, I was getting this error everytime another function tried to queue a task:

```
Error: Unsuccessful response status code. Request failed with status code 404
    at Gaxios._request (/workspace/node_modules/gcp-metadata/node_modules/gaxios/build/src/gaxios.js:141:23)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async metadataAccessor (/workspace/node_modules/gcp-metadata/build/src/index.js:110:21)
    at async GoogleAuth._GoogleAuth_getUniverseFromMetadataServer (/workspace/node_modules/google-auth-library/build/src/auth/googleauth.js:777:26)
    at async GoogleAuth.getUniverseDomain (/workspace/node_modules/google-auth-library/build/src/auth/googleauth.js:186:168)
    at async GoogleAuth.getApplicationDefaultAsync (/workspace/node_modules/google-auth-library/build/src/auth/googleauth.js:252:42)
    at async GoogleAuth.getClient (/workspace/node_modules/google-auth-library/build/src/auth/googleauth.js:674:17)
    at async getFunctionUrl (/workspace/lib/helpers/taskQueue.js:37:20)
    at async enqueueTask (/workspace/lib/helpers/taskQueue.js:55:23)
    at async Promise.all (index 0)
```

The issue seems to have been introduced by #1692 (cc @danielbankhead).

It suddenly appeard for me because Firebase doesn't respect your lockfile when deploying. My `package.json` specified `"google-auth-library": "^9.2.0"` but I was getting the latest `9.4.0` when deploying. I can resolve this issue by instead fixing my dependency to `"google-auth-library": "9.2.0"`. The error when goes away and I am able to queue tasks correctly.

#### Environment details

  - OS: macOS
  - Node.js version: 18.18.2
  - npm version: 9.8.1
  - `google-auth-library` version: 9.4.0

**Comment by UiiProDevs** [comment]
We're also seeing this issue when deploying an App Engine instance with Firebase after updating several packages. Manually installing google-auth-library@9.2.0 as a dependency also worked for us.

Here's our readout of `npm ls gaxios gcp-metadata google-auth-library` before doing the manual install:

```
+-- @google-cloud/logging-winston@6.0.0
| +-- @google-cloud/logging@11.0.0
| | +-- gcp-metadata@6.1.0
| | | `-- gaxios@6.1.1
| | `-- google-auth-library@9.4.0 deduped
| `-- google-auth-library@9.4.0
|   +-- gaxios@6.1.1
|   +-- gcp-metadata@6.1.0 deduped
|   `-- gtoken@7.0.1
|     `-- gaxios@6.1.1
+-- @google-cloud/pubsub@4.0.7
| +-- google-auth-library@9.4.0 deduped
| `-- google-gax@4.0.5
|   `-- google-auth-library@9.4.0 deduped
+-- @google-cloud/speech@6.1.0
| `-- @google-cloud/common@5.0.1
|   `-- google-auth-library@9.4.0 deduped
`-- firebase-admin@11.11.1
  +-- @google-cloud/firestore@6.8.0
  | `-- google-gax@3.6.1
  |   `-- google-auth-library@8.9.0
  |     +-- gaxios@5.1.3 deduped
  |     +-- gcp-metadata@5.3.0
  |     | `-- gaxios@5.1.3 deduped
  |     `-- gtoken@6.1.2
  |       `-- gaxios@5.1.3 deduped
  `-- @google-cloud/storage@6.12.0
    +-- gaxios@5.1.3
    `-- google-auth-library@8.9.0
      +-- gaxios@5.1.3 deduped
      +-- gcp-metadata@5.3.0
      | `-- gaxios@5.1.3 deduped
      `-- gtoken@6.1.2
        `-- gaxios@5.1.3 deduped
```

**Comment by danielbankhead** [comment]
@UiiProDevs 

Hmmm, I'm not seeing how it is possible to fail here with that setup:

https://github.com/googleapis/google-auth-library-nodejs/blob/e8966d19599f751b7b14364c67ce601b6e4793a0/src/auth/googleauth.ts#L314-L318

I see `firebase-admin` is pulling in outdated dependencies, therefore `gaxios` != `gaxios` (`5.1.3` vs `6.1.1`), which means `GaxiosError` != `GaxiosError`, however Auth v9 shouldn't be pulling in the older `GaxiosError`.

Still investigating...

**Comment by danielbankhead** [comment]
Finally able to reproduce.

There's a **very** strange and bizarre issue with `node`/`npm` where sometimes, depending on the order of the install, a dependency can require an older, undesired dependency, **even when explicitly specified not to**. Simple reproduction:

```sh
mkdir repro
cd repro
npm init -y
```

Create `index.mjs` with the following contents:

```ts
import {GoogleAuth} from 'google-auth-library';
import assert from 'assert';

try {
  const auth = await new GoogleAuth().getClient();
  console.log('No problem');
} catch (e) {
  console.log({e});
  assert.equal(e.status, 404);
}
```

Reproduction:
```sh
npm init -y
npm i @google-cloud/logging-winston
npm ls google-auth-library gaxios # lgtm
node index.mjs # No problem, works fine

rm -rf node_modules/ package-lock.json
npm i firebase-admin
npm ls google-auth-library gaxios # everything, _looks_ correct...
node index.mjs # Error, as GaxiosError != GaxiosError
```

Where `GaxiosError` != `GaxiosError`:

https://github.com/googleapis/google-auth-library-nodejs/blob/e8966d19599f751b7b14364c67ce601b6e4793a0/src/auth/googleauth.ts#L314-L318

**Comment by sebasrobert** [comment]
This is breaking our live operation right now, any idea how this will be released?

**Comment by danielbankhead** [comment]
@sebasrobert this will be released immediately upon approval. This should happen shortly as soon as the team is available. Alternatively, pinning to v9.2.0 of this library should work just fine.

**Comment by matt-oakes** [comment]
Thanks for the quick turn around. Just to confirm that when I upgrade to `9.4.1` everything works as expected 👍

**Comment by deepseed** [comment]
This issue broken my API even though my code does not directly use the ```google-auth-library```. It manifested as a 404 error when calling any API endpoint that used BigQuery, Pub/Sub or Secret Manager – which I assume use this library behind the scenes.

Installing the v9.2 package fixed the issue for me. (It was not previously in my packages.json.) I have not tested v9.4.1 yet.

**Comment by danielbankhead** [comment]
After extensive research and debugging I've found this TypeScript issue to be the root cause of this issue:
- https://dannyguo.medium.com/how-to-fix-instanceof-not-working-for-custom-errors-in-typescript-1df978100a27
- https://github.com/microsoft/TypeScript/issues/13965#issuecomment-278570200

**Comment by samschurter** [comment]
Thanks for getting this fixed so quick!

**Comment by SimonSchick** [comment]
We just got hit by this with the supposedly fixed version (9.4.1)

Attached is a `npm ls` of the dependency, can we get a little bit more of an explanation here? This is preventing us from upgrading dependencies.

<img width="569" alt="image" src="https://github.com/googleapis/google-auth-library-nodejs/assets/3259089/b9e7707e-3255-47c1-a964-f4dc5e78eb92">

**Comment by SimonSchick** [comment]
@danielbankhead for visibility, I can only assume some mix of google packages does not play nicely right now, I cannot create a minimal repro at this time.

**Comment by danielbankhead** [comment]
@SimonSchick hmmmm, that's very strange as it no longer depends on a particular instance of `GaxiosError`:
- https://github.com/googleapis/google-auth-library-nodejs/pull/1707/files#diff-535a540500eec341838bd88c84b1795313a8ff9b556bad87ef89fb2fca061630R314

Follow-ups:
- Is the error the exact same error message?
- Could you verify the `npm ls` is the same as deployed?
  - Note: if a `package-lock.json` isn't available or use the dependencies can drift between releases (personally, I use `npm ci` > `npm i` to ensure the `package-lock.json` is used).

**Comment by SimonSchick** [comment]
We do use yarn in this case so and our entire pipeline uses reproducable builds, we had to roll back our deployment after the version update and haven't had the time to investigate again.

**Comment by SimonSchick** [comment]
FYI this we are still experiencing this, all of our google deps are now consolidated (no duplicated), we are raising this with gcp as well.

**Comment by danielbankhead** [comment]
> FYI this we are still experiencing this, all of our google deps are now consolidated (no duplicated), we are raising this with gcp as well.
> 
> ![image](https://private-user-images.githubusercontent.com/3259089/314769277-8e06c04f-06a3-49ac-bb06-326db8790676.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA5ODI2MjAsIm5iZiI6MTcxMDk4MjMyMCwicGF0aCI6Ii8zMjU5MDg5LzMxNDc2OTI3Ny04ZTA2YzA0Zi0wNmEzLTQ5YWMtYmIwNi0zMjZkYjg3OTA2NzYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMyMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMjFUMDA1MjAwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MDgwMDhhNWM4YmUzY2Y2MDQ4NzE1NjhmZDFhNTNlNTU1ZTcyZDJmNWYwMmEyZDdkNjc3ODRkODA4OWUyOWZiYiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.qvcv-Dp5awmhTj7U36LjzK-NMmYu1zuRhieXXVP2CKo)

Do you mind providing a stack trace?
