### ISSUE TITLE
Error when using default credentials on GKE 

### ISSUE THREAD

**Issue by dorshay6** [googleapis/google-auth-library-nodejs#526]
```
(node:37) UnhandledPromiseRejectionWarning: Error: Unexpected error while acquiring application default credentials: Could not load the default credentials. Browse to https://developers.google.com/accounts/docs/application-default-credentials for more information.
    at GoogleAuth.<anonymous> (/usr/src/app/node_modules/@google-cloud/pubsub/node_modules/google-gax/node_modules/google-auth-library/build/src/auth/googleauth.js:248:31)
    at step (/usr/src/app/node_modules/@google-cloud/pubsub/node_modules/google-gax/node_modules/google-auth-library/build/src/auth/googleauth.js:47:23)
    at Object.next (/usr/src/app/node_modules/@google-cloud/pubsub/node_modules/google-gax/node_modules/google-auth-library/build/src/auth/googleauth.js:28:53)
    at fulfilled (/usr/src/app/node_modules/@google-cloud/pubsub/node_modules/google-gax/node_modules/google-auth-library/build/src/auth/googleauth.js:19:58)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

#### Environment details

  - OS: Ubuntu
  - Node.js version: 8 LTS
  - `google-auth-library` version: 2.0

#### Steps to reproduce

  1. Deploy a pod with version 2.0
  2. Wait some time - dont happend right away

**Comment by JustinBeckwith** [comment]
@dorshay6 apologies for the delay.  Out of curiosity - what's the size of your cluster?  How many nodes are you using?

**Comment by JustinBeckwith** [comment]
Since we haven't heard anything back for a while, we're going to go ahead and close this one out.  Please do let us know if you are still having any issues!
