### ISSUE TITLE
TypeError: jwt.split is not a function

### ISSUE THREAD

**Issue by 1silvertiger** [googleapis/google-auth-library-nodejs#616]
I am running a Node server on localhost with ngrok as per [this article](https://developers.google.com/search/docs/guides/debug). I can access the site fine from my browser. When I sign a user in with my Google Sign In button, I get the following error: 
```
TypeError: jwt.split is not a function
    at OAuth2Client.<anonymous> (C:\Users\1silv\OneDrive\Documents\Senior Project\Sage\app\node\node_modules\google-auth-library\build\src\auth\oauth2client.js:535:34)
    at Generator.next (<anonymous>)
    at C:\Users\1silv\OneDrive\Documents\Senior Project\Sage\app\node\node_modules\google-auth-library\build\src\auth\oauth2client.js:22:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\1silv\OneDrive\Documents\Senior Project\Sage\app\node\node_modules\google-auth-library\build\src\auth\oauth2client.js:18:12)
    at OAuth2Client.verifySignedJwtWithCertsAsync (C:\Users\1silv\OneDrive\Documents\Senior Project\Sage\app\node\node_modules\google-auth-library\build\src\auth\oauth2client.js:530:16)
    at OAuth2Client.<anonymous> (C:\Users\1silv\OneDrive\Documents\Senior Project\Sage\app\node\node_modules\google-auth-library\build\src\auth\oauth2client.js:421:38)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\1silv\OneDrive\Documents\Senior Project\Sage\app\node\node_modules\google-auth-library\build\src\auth\oauth2client.js:19:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```
The user signs in fine on the front end, and the correct information is displayed in the console. This is the function that runs when the user clicks the Sign in with Google button:
```
function onSignIn(googleUser) {
    // Useful data for your client-side scripts:
    var profile = googleUser.getBasicProfile();
    console.log("ID: " + profile.getId()); // Don't send this directly to your server!
    console.log('Full Name: ' + profile.getName());
    console.log('Given Name: ' + profile.getGivenName());
    console.log('Family Name: ' + profile.getFamilyName());
    console.log("Image URL: " + profile.getImageUrl());
    console.log("Email: " + profile.getEmail());

    // The ID token you need to pass to your backend:
    var id_token = googleUser.getAuthResponse().id_token;
    console.log("ID Token: " + id_token);

    // var xhr = new XMLHttpRequest();
    // xhr.open('POST', url);
    // xhr.setRequestHeader('Content-Type', 'application/x-www-form-urlencoded');
    // xhr.onload = function() {
    // console.log('Signed in as: ' + xhr.responseText);
    // };
    // xhr.send('idtoken=' + id_token);

    var data = {
        idtoken: id_token
    };

    $.ajax({
        type: "POST",
        url: url, 
        data: JSON.stringify(data),
        dataType: "json",
        success: function(data, status) {
            alert(data[d]);
        },
        error: function() {
            alert("Error");
        }
    });
    
}
```
I get the same error if I use `$.ajax` or `XMLHttpRequest`.

On the server, this is the code that runs:
```
app.post('/tokensignin', function(request, response, next){
  async function verify() {
    const ticket = await googleAuthClient.verifyIdToken({
      idToken: request.body.idtoken, 
      audience: GOOGLE_AUTH_CLIENT_ID, 
    });
    const payload = ticket.getPayload();
    const userid = payload['sub'];
    console.log(userid);
  }
  verify().catch(console.error);
});
```
All of the code is essentially copied and pasted from [this tutorial](https://developers.google.com/identity/sign-in/web/backend-auth).

I'm using Express 4.16.4, if that helps.

#### Environment details

  - OS: Windows 10
  - Node.js version: 10.15.0
  - npm version: 6.4.1
  - `google-auth-library` version: 3.0.1

**Comment by 1silvertiger** [comment]
I got the error to stop with I switched the way I was parsing `request.body.idtoken`, so I think it was not passing a string.

**Comment by JustinBeckwith** [comment]
Got it.  Does that mean you're all set now?

**Comment by 1silvertiger** [comment]
Yes.
