### ISSUE TITLE
Stopped working on node 6 (latest)

### ISSUE THREAD

**Issue by AndrewSolonovich** [googleapis/google-auth-library-nodejs#678]
Dependency package 'gaxios' was updated and google-auth stopped working on node ver 6.17.

This is the second time I encounter such breaking change somewhere in dependency of google-auth library.
Is it possible to embed all dependencies for the specific version of the library? 
Since there is no documentation on how to authenticate to GCP without this auth library, it becomes a big problem to use it - you must spend time and fix\find workaround every time after someone updates some dependency..

Now it throws next error:

```
async function request(opts) {
      ^^^^^^^^

SyntaxError: Unexpected token function
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.(anonymous) (/builds/apigee/testrunner/node_modules/grunt-base/node_modules/gcp-metadata/build/src/index.js:17:18)
    at Module._compile (module.js:577:32)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.(anonymous) (/builds/apigee/testrunner/node_modules/grunt-base/node_modules/google-auth-library/build/src/auth/googleauth.js:28:21)
    at Module._compile (module.js:577:32)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
```

#### Environment details

  - OS: no matter
  - Node.js version: 6.17 (latest 6)
  - npm version: 3.10.10
  - `google-auth-library` version: 2.0.3

#### Steps to reproduce

  1. using docker node 6, run any nodejs code which uses google-auth

**Comment by JustinBeckwith** [comment]
Greetings folks!  There was an errant release of the `gaxios` npm module which dropped support for node.js 6.x in a patch release.  That release was rolled back, and the dist-tag was appropriately set. 

Please:
- delete your `package-lock.json` or `yarn.lock`
- run `npm install`

Let us know if you're still having any problems!
