### ISSUE TITLE
the authentication library relies on gaxios setting application/json header

### ISSUE THREAD

**Issue by bcoe** [googleapis/google-auth-library-nodejs#929]
There is logic in our authentication flow that relies on the upstream gaxios library overwriting the content-type header with `application/json`. We should dig into why this is necessary, and explicitly set this header in the library.

**Comment by herrsiim** [comment]
Will this be fixed any time soon? Could you please provide us a workaround until then?

**Comment by bcoe** [comment]
@herrsiim could you provide an example of the problem you are running into? The problem in gaxios that was breaking authentication should already have been rolled back.

**Comment by herrsiim** [comment]
I'm trying to ask for a token using the "Application Default Credentials" method. I have set an "GOOGLE_APPLICATION_CREDENTIALS" enviroment variable. 

When I run this code with node: 

```
const { GoogleAuth } = require('google-auth-library');

async function main() {
    const auth = new GoogleAuth({
        scopes: 'https://www.googleapis.com/auth/cloud-platform'
    });
    const client = await auth.getClient();
    const projectId = await auth.getProjectId();
    const url = `https://dns.googleapis.com/dns/v1/projects/${projectId}`;
    const res = await client.request({ url });
    console.log(res.data);
}

main().catch(console.error);
```

This is the answer which I get:
```
GaxiosError: Forbidden
    at Gaxios._request (C:\Projects\goto-and-bot\node_modules\gaxios\build\src\gaxios.js:86:23)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async JWT.requestAsync (C:\Projects\goto-and-bot\node_modules\google-auth-library\build\src\auth\oauth2client.js:343:18)
    at async getToken (C:\Projects\goto-and-bot\app.js:27:17) {
  response: {
    config: {
      url: 'https://dns.googleapis.com/dns/v1/projects/gotoandbot-kdwedq',
      headers: [Object],
      params: [Object: null prototype] {},
      paramsSerializer: [Function: paramsSerializer],
      validateStatus: [Function: validateStatus],
      responseType: 'json',
      method: 'GET'
    },
    data: { error: [Object] },
    headers: {
      'alt-svc': 'h3-29=":443"; ma=2592000,h3-27=":443"; ma=2592000,h3-25=":443"; ma=2592000,h3-T050=":443"; ma=2592000,h3-Q050=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000,quic=":443"; ma=2592000; v="46,43"',
      'cache-control': 'private',
      connection: 'close',
      'content-encoding': 'gzip',
      'content-type': 'application/json; charset=UTF-8',
      date: 'Thu, 16 Jul 2020 10:20:01 GMT',
      server: 'ESF',
      'transfer-encoding': 'chunked',
      vary: 'Origin, X-Origin, Referer',
      'x-content-type-options': 'nosniff',
      'x-frame-options': 'SAMEORIGIN',
      'x-xss-protection': '0'
    },
    status: 403,
    statusText: 'Forbidden',
    request: {
      responseURL: 'https://dns.googleapis.com/dns/v1/projects/gotoandbot-kdwedq'
    }
  },
  config: {
    url: 'https://dns.googleapis.com/dns/v1/projects/gotoandbot-kdwedq',
    headers: {
      Authorization: 'Bearer ya29.c.Ko8B1AeJrs4BAkjErokYrtph3oXCVNoqBcL8Eg1QfaOIojcMn9CvJG47TNxr7wv15XbvbreVR6pzLedNB60t1trRDxnrE_TFzknE_p5vsggBv6kmxABoDRLKmchypITpvWDoEbFMDwB3qCEbq4MxWTXrgqqzyYX6hz0_FBT5ucLqSD-9VO12WbQhZSep-92u97A',
      'User-Agent': 'google-api-nodejs-client/6.0.5',
      'x-goog-api-client': 'gl-node/14.4.0 auth/6.0.5',
      Accept: 'application/json'
    },
    params: [Object: null prototype] {},
    paramsSerializer: [Function: paramsSerializer],
    validateStatus: [Function: validateStatus],
    responseType: 'json',
    method: 'GET'
  },
  code: 403,
  errors: [ { message: 'Forbidden', domain: 'global', reason: 'forbidden' } ]
}
```

In short, it get's me the Authorization header, but the error in the front breaks my application and all I get returned is an error.

**Comment by bcoe** [comment]
@herrsiim  this seems like potentially an unrelated issue to me, related to the request you are making not being allowed with the credentials that have been returned.

Depending on what your are trying to do, it might be worth looking at the [@google-cloud/dns](https://github.com/googleapis/nodejs-dns) repo.

**Comment by JustinBeckwith** [comment]
I'm fairly certain this was addressed in https://github.com/googleapis/gaxios/pull/374
